package se.rajo.cat_api.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import se.rajo.cat_api.model.Cat;

public interface CatRepository extends JpaRepository<Cat, Integer> {
    // We can add custom queries here to be able to integrate with the Cat Entity
    // Except for the methods auto generated by JpaRepository
}
