spring.application.name=cat_api

# Database configuration
spring.datasource.url = jdbc:h2:mem:cat_db
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = password
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect

# Activate H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Serverport
server.port=8080
